  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    restart: always
    env_file:
      - backend/.env-non-dev
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - custom

  fastapi_app:
    env_file:
      - backend/.env-non-dev
    build:
      context: backend/
#    image: menoitami/task-tracker
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db
      - redis

networks:
  custom:
    driver: bridge

volumes:
  db-data:
