"""empty message

Revision ID: 026b2ba40902
Revises: d484ca80f52c
Create Date: 2024-07-15 17:30:39.244328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026b2ba40902'
down_revision: Union[str, None] = 'd484ca80f52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'asana_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('asana_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
