"""empty message

Revision ID: 080608804313
Revises: 8450eb23487e
Create Date: 2024-08-07 18:43:45.458676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "080608804313"
down_revision: Union[str, None] = "8450eb23487e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_org",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column(
            "permissions", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("organization_owner_id_fkey", "organization", type_="foreignkey")
    op.drop_column("organization", "owner_id")
    op.drop_constraint("user_organization_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "organization_id")
    op.drop_constraint("user_task_user_id_fkey", "user_task", type_="foreignkey")
    op.create_foreign_key(
        None, "user_task", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_task", type_="foreignkey")
    op.create_foreign_key(
        "user_task_user_id_fkey", "user_task", "user", ["user_id"], ["id"]
    )
    op.add_column(
        "user",
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "user_organization_id_fkey", "user", "organization", ["organization_id"], ["id"]
    )
    op.add_column(
        "organization",
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "organization_owner_id_fkey",
        "organization",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("user_org")
    # ### end Alembic commands ###
