"""empty message

Revision ID: 8ae5ab3e8ad8
Revises: 080608804313
Create Date: 2024-08-11 03:18:25.057730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae5ab3e8ad8'
down_revision: Union[str, None] = '080608804313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('group', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'group', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.alter_column('group', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('group', 'project_id')
    # ### end Alembic commands ###
