"""empty message

Revision ID: d1dc797c28e0
Revises: 8ae5ab3e8ad8
Create Date: 2024-08-11 03:36:23.363282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dc797c28e0'
down_revision: Union[str, None] = '8ae5ab3e8ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_group_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_group_id_fkey', 'task', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
