"""empty message

Revision ID: e43c5e9fc331
Revises: c8416d4c2815
Create Date: 2024-08-04 15:44:03.229087

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, BYTEA, UUID

# revision identifiers, used by Alembic.
revision: str = 'e43c5e9fc331'
down_revision: Union[str, None] = 'c8416d4c2815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles = [
        {
            'name': 'unauthorized',
            'permissions': {
                'user': {'create': True, 'read': False, 'update': False, 'delete': False},
                'task': {'create': False, 'read': False, 'update': False, 'delete': False},
                'group': {'create': False, 'read': False, 'update': False, 'delete': False},
                'project': {'create': False, 'read': False, 'update': False, 'delete': False},
                'organization': {'create': False, 'read': False, 'update': False, 'delete': False},
                'role': {'create': False, 'read': False, 'update': False, 'delete': False}
            }
        },
        {
            'name': 'user',
            'permissions': {
                'user': {'create': True, 'read': True, 'update': True, 'delete': True},
                'task': {'create': True, 'read': True, 'update': True, 'delete': True},
                'group': {'create': True, 'read': True, 'update': True, 'delete': True},
                'project': {'create': True, 'read': True, 'update': True, 'delete': True},
                'organization': {'create': False, 'read': False, 'update': False, 'delete': False},
                'role': {'create': False, 'read': False, 'update': False, 'delete': False}
            }
        },
        {
            'name': 'enterprise',
            'permissions': {
                'user': {'create': True, 'read': True, 'update': True, 'delete': True},
                'task': {'create': True, 'read': True, 'update': True, 'delete': True},
                'group': {'create': True, 'read': True, 'update': True, 'delete': True},
                'project': {'create': True, 'read': True, 'update': True, 'delete': True},
                'organization': {'create': True, 'read': True, 'update': True, 'delete': True},
                'role': {'create': False, 'read': False, 'update': False, 'delete': False}
            }
        },
        {
            'name': 'admin',
            'permissions': {
                'user': {'create': True, 'read': True, 'update': True, 'delete': True},
                'task': {'create': True, 'read': True, 'update': True, 'delete': True},
                'group': {'create': True, 'read': True, 'update': True, 'delete': True},
                'project': {'create': True, 'read': True, 'update': True, 'delete': True},
                'organization': {'create': True, 'read': True, 'update': True, 'delete': True},
                'role': {'create': True, 'read': True, 'update': True, 'delete': True}
            }
        }
    ]

    op.bulk_insert(
        sa.table('role',
                 sa.Column('name', sa.String),
                 sa.Column('permissions', JSON)
                 ),
        roles
    )
    admin_user = {
        'id': uuid4(),
        'first_name': 'admin',
        'last_name': 'admin',
        'role_id': 4,  # ID роли 'admin'
        'email': 'admin@admin.com',
        'is_email_confirmed': True,
        'registered_at': datetime.utcnow(),
        'hashed_password': b'$2b$12$2p8wTdWX6ftccz4vrSVeveilewaicYyY8xk6Ie.YO5/Ywk4.d6.LS',  # Хэш пароля для "adminpassword"
        'is_active': True,
        'is_verified': True,
        'tg_id': None,
        'tg_settings': None,
        'organization_id': None,
        'pathfile': None,
        'github_name': None
    }

    op.bulk_insert(
        sa.table('user',
                 sa.Column('id', UUID),
                 sa.Column('first_name', sa.String),
                 sa.Column('last_name', sa.String),
                 sa.Column('role_id', sa.Integer),
                 sa.Column('email', sa.String),
                 sa.Column('is_email_confirmed', sa.Boolean),
                 sa.Column('registered_at', sa.DateTime),
                 sa.Column('hashed_password', BYTEA),
                 sa.Column('is_active', sa.Boolean),
                 sa.Column('is_verified', sa.Boolean),
                 sa.Column('tg_id', sa.String),
                 sa.Column('tg_settings', JSON),
                 sa.Column('organization_id', sa.Integer),
                 sa.Column('pathfile', sa.String),
                 sa.Column('github_name', sa.String)
                 ),
        [admin_user]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
