"""empty message

Revision ID: d484ca80f52c
Revises: 0f0e4919f05f
Create Date: 2024-04-13 22:28:54.959293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd484ca80f52c'
down_revision: Union[str, None] = '0f0e4919f05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_name')
    # ### end Alembic commands ###
