"""empty message

Revision ID: fe6efc6ea19a
Revises: 31cb5ae0d33a
Create Date: 2024-04-13 21:07:38.850742

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6efc6ea19a'
down_revision: Union[str, None] = '31cb5ae0d33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('task', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'group', ['group_id'], ['id'])

    # Приведение типа столбца `duration` к типу `interval` с использованием USING для корректного преобразования данных


    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'group_id')
    op.drop_table('group')

    # Восстановление типа данных для столбца `duration`, если необходимо
    # Например, если `duration` был ранее строкой или другим типом, который использовался до миграции.
    # Убедитесь, что знаете исходный тип данных, или этот шаг может быть пропущен, если тип данных изначально был установлен правильно.
    # op.execute('ALTER TABLE task ALTER COLUMN duration TYPE <your_original_type> USING duration::<your_original_type>')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
